### ISSUE TITLE
Not working on 2.2.9

### ISSUE THREAD

**Issue by baxterdmutt** [adamzammit/LimeSurvey-Signature-Question#1]
This no longer works on 6.2.9. I think it’s that you can no longer chose a question theme. Instead it gets installed as a question type and you can choose it. But when it’s chosen, it’s just a regular short text field.

**Comment by adamzammit** [comment]
Hi @baxterdmutt  - can you please try the 1.0.1 release - this hides the text box.
I've tested it on 6.3.4 and the signature box is there.

**Comment by baxterdmutt** [comment]
I got this working. I think the zip file has an issue. Unzipping into Limesurvey/upload/theme/survey/question/ and then unzipping creates an extra /signature directory. So it looked like Limesurvey/upload/theme/survey/question/signature/signature/answer…. This won’t work. Move everything back from the 2nd signature directory to the 1st signature directory and then delete the second one. It should look like 
Limesurvey/upload/theme/survey/question/signature/answer….

**Comment by baxterdmutt** [comment]
It still does not work. 
If I unzip into the upload/themes/question folder Signaturepad is not in the question type. If I change the folder that the zip created (LimeSurvey-Signature-Question-main) to “signature” the question type shows up but the question is still short free text when previewed.

**Comment by baxterdmutt** [comment]
To make it work I renamed “LimeSurvey-Signature-Question-main” to signature. The directory structure was then “upload/themes/question/signature/signature/survey/questions..”
I moved what was in the 2nd signature folder up one so that it looks like;
upload/themes/question/signature/survey/questions
It works like this.
