### ISSUE TITLE
Pen Color

### ISSUE THREAD

**Issue by baxterdmutt** [adamzammit/LimeSurvey-Signature-Question#3]
I see you updated the theme to add a pen color.  I'm wondering what I need to do to get it to work?  I've added the new files but the color does not change. I uninstalled and reinstalled but no luck. Maybe I'm entering the ccs wrong. What should that look like.

**Comment by baxterdmutt** [comment]
If it helps, this is what the inspect element looks like. To my newbie eye it looks like none of the colors are sent: 

```
/*<![CDATA[*/

                if(window.basicThemeScripts === undefined){ 
                    window.basicThemeScripts = new ThemeScripts(); 
                } 
                basicThemeScripts.initGlobal(); 
                

            try{ 
                triggerEmClassChange(); 
            } catch(e) {
                console.ls.warn('triggerEmClassChange could not be run. Is survey.js/old_template_core_pre.js correctly loaded?');
            }

triggerEmRelevance();
jQuery(document).off('pjax:scriptcomplete.mainBottom').on('ready pjax:scriptcomplete.mainBottom', function() {

    const canvas = document.getElementById('signature-pad444468X104X1879');
    const clearButton = document.getElementById('signature-pad-clear444468X104X1879');
    const signaturePad = new SignaturePad(canvas, {
      penColor: '',
      backgroundColor: '',
      minWidth: '',
      maxWidth: ''
    });
    
    signaturePad.addEventListener('endStroke', () => {
      $('#answer444468X104X1879').val(signaturePad.toDataURL());
    });
    
    clearButton.addEventListener('click', function (event) {
     signaturePad.clear();
     $('#answer444468X104X1879').val(signaturePad.toDataURL());
    });

    signaturePad.fromDataURL($('#answer444468X104X1879').val());
    
activateActionLink();
activateConfirmButton();
basicThemeScripts.initTopMenuLanguageChanger('.ls-language-link ', 'form#limesurvey'); 

    $('#limesurvey').append('<input type="hidden" name="ajax" value="off" id="ajax" />');
    
updateMandatoryErrorClass();
});
/*]]>*/
```

**Comment by adamzammit** [comment]
what version of LimeSurvey are you using?

**Comment by baxterdmutt** [comment]
6.3.4RogerOn Dec 10, 2023, at 19:24, Adam Zammit ***@***.***> wrote:﻿
what version of LimeSurvey are you using?

**Comment by adamzammit** [comment]
I have tested it on 6.3.9 and it works fine for me.

Created a signature question, and changed the pen colour to "red" and it became red.

Please give that a try

**Comment by baxterdmutt** [comment]
Hmm, exactly what are you entering in the css for this to work. I must be doing something wrong. RogerOn Dec 14, 2023, at 18:31, Adam Zammit ***@***.***> wrote:﻿
I have tested it on 6.3.9 and it works fine for me.
Created a signature question, and changed the pen colour to "red" and it became red.
Please give that a try

**Comment by adamzammit** [comment]
Hi again,

Please see this video on how to change the pen colour:


https://github.com/adamzammit/LimeSurvey-Signature-Question/assets/1452303/4027e1c0-36ce-41a7-971e-30473ba61fd8



Adam

**Comment by baxterdmutt** [comment]
Thanks but if it was that easy I would harve figured it out. I don’t have those settings.  Could it be because I use extends_fruity theme. I only use extend to change the background of a couple questions by adding background setting in custom.css I can’t imagine that is the problem. RogerOn Dec 20, 2023, at 19:39, Adam Zammit ***@***.***> wrote:﻿
Hi again,
Please see this video on how to change the pen colour:
https://github.com/adamzammit/LimeSurvey-Signature-Question/assets/1452303/4027e1c0-36ce-41a7-971e-30473ba61fd8
Adam

**Comment by baxterdmutt** [comment]
Hmm, I think I would have figured that out.  My screen does not have any of the setting s related to the pen. The "Display" tab shows the standard settings for test questions. I did reinstall signature pad, it works, m but will not show any of the settings.  I am using fruity extended theme so I tried changing to other themes and it has not made any difference.

**Comment by baxterdmutt** [comment]
The solution for me was to modify the config.xml file and move everything in that was 
"custom attribute" up to "attributes" and then delete the list of "custom attributes"
It now works like that.
